name: demo

on: push

jobs:
  first_demo_job:
    name: The first demo job
    runs-on: ubuntu-latest
    steps:
      - name: Show the demo running
        env:
          Greeting: Hello
        run: |
          -name: "Say Hello"
           echo "Hello Happy $DAY_OF_WEEK!"
