name: npm test

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        node_version: [12.x]

    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v1

        with:

          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run build --if-present

      - run: npm test
        env:

      depoly:
        needs: build
        runs-on: unbunto-latest
        steps:
            - uses: actions/checkout@master
            - uses: jakejarvis/s3-sync-action@master
            - uses: aws-actions/configure-aws-credentials@v1
            with:
              args: --acl public-read --follow-symlinks --delete
            env:
              AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }} 
              AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
              AWS_REGION: "us-east-1"
          - name: Copy to S3
            run: aws s3 sync ./build/. s3://jd-littletiers
